// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockdb

import (
	"context"

	"github.com/alwitt/rest-pty/db"
	"github.com/alwitt/rest-pty/models"
	mock "github.com/stretchr/testify/mock"
)

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// DefineNewSession provides a mock function for the type Database
func (_mock *Database) DefineNewSession(ctx context.Context, name string, description *string, command models.SessionCommand, outputBufferCapacity int64, driverParams interface{}, workspaceName *string) (models.Session, error) {
	ret := _mock.Called(ctx, name, description, command, outputBufferCapacity, driverParams, workspaceName)

	if len(ret) == 0 {
		panic("no return value specified for DefineNewSession")
	}

	var r0 models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, models.SessionCommand, int64, interface{}, *string) (models.Session, error)); ok {
		return returnFunc(ctx, name, description, command, outputBufferCapacity, driverParams, workspaceName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, models.SessionCommand, int64, interface{}, *string) models.Session); ok {
		r0 = returnFunc(ctx, name, description, command, outputBufferCapacity, driverParams, workspaceName)
	} else {
		r0 = ret.Get(0).(models.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, models.SessionCommand, int64, interface{}, *string) error); ok {
		r1 = returnFunc(ctx, name, description, command, outputBufferCapacity, driverParams, workspaceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_DefineNewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineNewSession'
type Database_DefineNewSession_Call struct {
	*mock.Call
}

// DefineNewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - command models.SessionCommand
//   - outputBufferCapacity int64
//   - driverParams interface{}
//   - workspaceName *string
func (_e *Database_Expecter) DefineNewSession(ctx interface{}, name interface{}, description interface{}, command interface{}, outputBufferCapacity interface{}, driverParams interface{}, workspaceName interface{}) *Database_DefineNewSession_Call {
	return &Database_DefineNewSession_Call{Call: _e.mock.On("DefineNewSession", ctx, name, description, command, outputBufferCapacity, driverParams, workspaceName)}
}

func (_c *Database_DefineNewSession_Call) Run(run func(ctx context.Context, name string, description *string, command models.SessionCommand, outputBufferCapacity int64, driverParams interface{}, workspaceName *string)) *Database_DefineNewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 models.SessionCommand
		if args[3] != nil {
			arg3 = args[3].(models.SessionCommand)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 interface{}
		if args[5] != nil {
			arg5 = args[5].(interface{})
		}
		var arg6 *string
		if args[6] != nil {
			arg6 = args[6].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *Database_DefineNewSession_Call) Return(session models.Session, err error) *Database_DefineNewSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *Database_DefineNewSession_Call) RunAndReturn(run func(ctx context.Context, name string, description *string, command models.SessionCommand, outputBufferCapacity int64, driverParams interface{}, workspaceName *string) (models.Session, error)) *Database_DefineNewSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type Database
func (_mock *Database) DeleteSession(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type Database_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Database_Expecter) DeleteSession(ctx interface{}, name interface{}) *Database_DeleteSession_Call {
	return &Database_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, name)}
}

func (_c *Database_DeleteSession_Call) Run(run func(ctx context.Context, name string)) *Database_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DeleteSession_Call) Return(err error) *Database_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, name string) error) *Database_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByName provides a mock function for the type Database
func (_mock *Database) GetSessionByName(ctx context.Context, name string) (models.Session, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByName")
	}

	var r0 models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Session, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Session); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(models.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetSessionByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByName'
type Database_GetSessionByName_Call struct {
	*mock.Call
}

// GetSessionByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Database_Expecter) GetSessionByName(ctx interface{}, name interface{}) *Database_GetSessionByName_Call {
	return &Database_GetSessionByName_Call{Call: _e.mock.On("GetSessionByName", ctx, name)}
}

func (_c *Database_GetSessionByName_Call) Run(run func(ctx context.Context, name string)) *Database_GetSessionByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_GetSessionByName_Call) Return(session models.Session, err error) *Database_GetSessionByName_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *Database_GetSessionByName_Call) RunAndReturn(run func(ctx context.Context, name string) (models.Session, error)) *Database_GetSessionByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function for the type Database
func (_mock *Database) ListSessions(ctx context.Context, filters db.SessionQueryFilter) ([]models.Session, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.SessionQueryFilter) ([]models.Session, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.SessionQueryFilter) []models.Session); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.SessionQueryFilter) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type Database_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - filters db.SessionQueryFilter
func (_e *Database_Expecter) ListSessions(ctx interface{}, filters interface{}) *Database_ListSessions_Call {
	return &Database_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, filters)}
}

func (_c *Database_ListSessions_Call) Run(run func(ctx context.Context, filters db.SessionQueryFilter)) *Database_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.SessionQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.SessionQueryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_ListSessions_Call) Return(sessions []models.Session, err error) *Database_ListSessions_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *Database_ListSessions_Call) RunAndReturn(run func(ctx context.Context, filters db.SessionQueryFilter) ([]models.Session, error)) *Database_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSessionIdle provides a mock function for the type Database
func (_mock *Database) MarkSessionIdle(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for MarkSessionIdle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkSessionIdle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSessionIdle'
type Database_MarkSessionIdle_Call struct {
	*mock.Call
}

// MarkSessionIdle is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Database_Expecter) MarkSessionIdle(ctx interface{}, name interface{}) *Database_MarkSessionIdle_Call {
	return &Database_MarkSessionIdle_Call{Call: _e.mock.On("MarkSessionIdle", ctx, name)}
}

func (_c *Database_MarkSessionIdle_Call) Run(run func(ctx context.Context, name string)) *Database_MarkSessionIdle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkSessionIdle_Call) Return(err error) *Database_MarkSessionIdle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkSessionIdle_Call) RunAndReturn(run func(ctx context.Context, name string) error) *Database_MarkSessionIdle_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSessionReady provides a mock function for the type Database
func (_mock *Database) MarkSessionReady(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for MarkSessionReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkSessionReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSessionReady'
type Database_MarkSessionReady_Call struct {
	*mock.Call
}

// MarkSessionReady is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Database_Expecter) MarkSessionReady(ctx interface{}, name interface{}) *Database_MarkSessionReady_Call {
	return &Database_MarkSessionReady_Call{Call: _e.mock.On("MarkSessionReady", ctx, name)}
}

func (_c *Database_MarkSessionReady_Call) Run(run func(ctx context.Context, name string)) *Database_MarkSessionReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkSessionReady_Call) Return(err error) *Database_MarkSessionReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkSessionReady_Call) RunAndReturn(run func(ctx context.Context, name string) error) *Database_MarkSessionReady_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function for the type Database
func (_mock *Database) Ready() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type Database_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *Database_Expecter) Ready() *Database_Ready_Call {
	return &Database_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *Database_Ready_Call) Run(run func()) *Database_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_Ready_Call) Return(err error) *Database_Ready_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_Ready_Call) RunAndReturn(run func() error) *Database_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionCommand provides a mock function for the type Database
func (_mock *Database) UpdateSessionCommand(ctx context.Context, name string, newCommand models.SessionCommand) error {
	ret := _mock.Called(ctx, name, newCommand)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.SessionCommand) error); ok {
		r0 = returnFunc(ctx, name, newCommand)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateSessionCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionCommand'
type Database_UpdateSessionCommand_Call struct {
	*mock.Call
}

// UpdateSessionCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - newCommand models.SessionCommand
func (_e *Database_Expecter) UpdateSessionCommand(ctx interface{}, name interface{}, newCommand interface{}) *Database_UpdateSessionCommand_Call {
	return &Database_UpdateSessionCommand_Call{Call: _e.mock.On("UpdateSessionCommand", ctx, name, newCommand)}
}

func (_c *Database_UpdateSessionCommand_Call) Run(run func(ctx context.Context, name string, newCommand models.SessionCommand)) *Database_UpdateSessionCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.SessionCommand
		if args[2] != nil {
			arg2 = args[2].(models.SessionCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateSessionCommand_Call) Return(err error) *Database_UpdateSessionCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateSessionCommand_Call) RunAndReturn(run func(ctx context.Context, name string, newCommand models.SessionCommand) error) *Database_UpdateSessionCommand_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionDescription provides a mock function for the type Database
func (_mock *Database) UpdateSessionDescription(ctx context.Context, name string, newDescription *string) error {
	ret := _mock.Called(ctx, name, newDescription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionDescription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) error); ok {
		r0 = returnFunc(ctx, name, newDescription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateSessionDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionDescription'
type Database_UpdateSessionDescription_Call struct {
	*mock.Call
}

// UpdateSessionDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - newDescription *string
func (_e *Database_Expecter) UpdateSessionDescription(ctx interface{}, name interface{}, newDescription interface{}) *Database_UpdateSessionDescription_Call {
	return &Database_UpdateSessionDescription_Call{Call: _e.mock.On("UpdateSessionDescription", ctx, name, newDescription)}
}

func (_c *Database_UpdateSessionDescription_Call) Run(run func(ctx context.Context, name string, newDescription *string)) *Database_UpdateSessionDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateSessionDescription_Call) Return(err error) *Database_UpdateSessionDescription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateSessionDescription_Call) RunAndReturn(run func(ctx context.Context, name string, newDescription *string) error) *Database_UpdateSessionDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionDriver provides a mock function for the type Database
func (_mock *Database) UpdateSessionDriver(ctx context.Context, name string, driverParams interface{}) error {
	ret := _mock.Called(ctx, name, driverParams)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionDriver")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = returnFunc(ctx, name, driverParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateSessionDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionDriver'
type Database_UpdateSessionDriver_Call struct {
	*mock.Call
}

// UpdateSessionDriver is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - driverParams interface{}
func (_e *Database_Expecter) UpdateSessionDriver(ctx interface{}, name interface{}, driverParams interface{}) *Database_UpdateSessionDriver_Call {
	return &Database_UpdateSessionDriver_Call{Call: _e.mock.On("UpdateSessionDriver", ctx, name, driverParams)}
}

func (_c *Database_UpdateSessionDriver_Call) Run(run func(ctx context.Context, name string, driverParams interface{})) *Database_UpdateSessionDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateSessionDriver_Call) Return(err error) *Database_UpdateSessionDriver_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateSessionDriver_Call) RunAndReturn(run func(ctx context.Context, name string, driverParams interface{}) error) *Database_UpdateSessionDriver_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionName provides a mock function for the type Database
func (_mock *Database) UpdateSessionName(ctx context.Context, name string, newName string) error {
	ret := _mock.Called(ctx, name, newName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateSessionName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionName'
type Database_UpdateSessionName_Call struct {
	*mock.Call
}

// UpdateSessionName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - newName string
func (_e *Database_Expecter) UpdateSessionName(ctx interface{}, name interface{}, newName interface{}) *Database_UpdateSessionName_Call {
	return &Database_UpdateSessionName_Call{Call: _e.mock.On("UpdateSessionName", ctx, name, newName)}
}

func (_c *Database_UpdateSessionName_Call) Run(run func(ctx context.Context, name string, newName string)) *Database_UpdateSessionName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateSessionName_Call) Return(err error) *Database_UpdateSessionName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateSessionName_Call) RunAndReturn(run func(ctx context.Context, name string, newName string) error) *Database_UpdateSessionName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionOutputBufCapacity provides a mock function for the type Database
func (_mock *Database) UpdateSessionOutputBufCapacity(ctx context.Context, name string, newCap int64) error {
	ret := _mock.Called(ctx, name, newCap)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionOutputBufCapacity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, name, newCap)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateSessionOutputBufCapacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionOutputBufCapacity'
type Database_UpdateSessionOutputBufCapacity_Call struct {
	*mock.Call
}

// UpdateSessionOutputBufCapacity is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - newCap int64
func (_e *Database_Expecter) UpdateSessionOutputBufCapacity(ctx interface{}, name interface{}, newCap interface{}) *Database_UpdateSessionOutputBufCapacity_Call {
	return &Database_UpdateSessionOutputBufCapacity_Call{Call: _e.mock.On("UpdateSessionOutputBufCapacity", ctx, name, newCap)}
}

func (_c *Database_UpdateSessionOutputBufCapacity_Call) Run(run func(ctx context.Context, name string, newCap int64)) *Database_UpdateSessionOutputBufCapacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateSessionOutputBufCapacity_Call) Return(err error) *Database_UpdateSessionOutputBufCapacity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateSessionOutputBufCapacity_Call) RunAndReturn(run func(ctx context.Context, name string, newCap int64) error) *Database_UpdateSessionOutputBufCapacity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionRunMode provides a mock function for the type Database
func (_mock *Database) UpdateSessionRunMode(ctx context.Context, name string, newMode models.SessionRunnerModeTypeENUMType) error {
	ret := _mock.Called(ctx, name, newMode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionRunMode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.SessionRunnerModeTypeENUMType) error); ok {
		r0 = returnFunc(ctx, name, newMode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateSessionRunMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionRunMode'
type Database_UpdateSessionRunMode_Call struct {
	*mock.Call
}

// UpdateSessionRunMode is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - newMode models.SessionRunnerModeTypeENUMType
func (_e *Database_Expecter) UpdateSessionRunMode(ctx interface{}, name interface{}, newMode interface{}) *Database_UpdateSessionRunMode_Call {
	return &Database_UpdateSessionRunMode_Call{Call: _e.mock.On("UpdateSessionRunMode", ctx, name, newMode)}
}

func (_c *Database_UpdateSessionRunMode_Call) Run(run func(ctx context.Context, name string, newMode models.SessionRunnerModeTypeENUMType)) *Database_UpdateSessionRunMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.SessionRunnerModeTypeENUMType
		if args[2] != nil {
			arg2 = args[2].(models.SessionRunnerModeTypeENUMType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateSessionRunMode_Call) Return(err error) *Database_UpdateSessionRunMode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateSessionRunMode_Call) RunAndReturn(run func(ctx context.Context, name string, newMode models.SessionRunnerModeTypeENUMType) error) *Database_UpdateSessionRunMode_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionWorkspaceName provides a mock function for the type Database
func (_mock *Database) UpdateSessionWorkspaceName(ctx context.Context, name string, newWorkspaceName *string) error {
	ret := _mock.Called(ctx, name, newWorkspaceName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionWorkspaceName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) error); ok {
		r0 = returnFunc(ctx, name, newWorkspaceName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateSessionWorkspaceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionWorkspaceName'
type Database_UpdateSessionWorkspaceName_Call struct {
	*mock.Call
}

// UpdateSessionWorkspaceName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - newWorkspaceName *string
func (_e *Database_Expecter) UpdateSessionWorkspaceName(ctx interface{}, name interface{}, newWorkspaceName interface{}) *Database_UpdateSessionWorkspaceName_Call {
	return &Database_UpdateSessionWorkspaceName_Call{Call: _e.mock.On("UpdateSessionWorkspaceName", ctx, name, newWorkspaceName)}
}

func (_c *Database_UpdateSessionWorkspaceName_Call) Run(run func(ctx context.Context, name string, newWorkspaceName *string)) *Database_UpdateSessionWorkspaceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateSessionWorkspaceName_Call) Return(err error) *Database_UpdateSessionWorkspaceName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateSessionWorkspaceName_Call) RunAndReturn(run func(ctx context.Context, name string, newWorkspaceName *string) error) *Database_UpdateSessionWorkspaceName_Call {
	_c.Call.Return(run)
	return _c
}
