// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksession

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// newCoreDriver creates a new instance of coreDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newCoreDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *coreDriver {
	mock := &coreDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// coreDriver is an autogenerated mock type for the coreDriver type
type coreDriver struct {
	mock.Mock
}

type coreDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *coreDriver) EXPECT() *coreDriver_Expecter {
	return &coreDriver_Expecter{mock: &_m.Mock}
}

// PipeInput provides a mock function for the type coreDriver
func (_mock *coreDriver) PipeInput(input io.Reader) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for PipeInput")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// coreDriver_PipeInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PipeInput'
type coreDriver_PipeInput_Call struct {
	*mock.Call
}

// PipeInput is a helper method to define mock.On call
//   - input io.Reader
func (_e *coreDriver_Expecter) PipeInput(input interface{}) *coreDriver_PipeInput_Call {
	return &coreDriver_PipeInput_Call{Call: _e.mock.On("PipeInput", input)}
}

func (_c *coreDriver_PipeInput_Call) Run(run func(input io.Reader)) *coreDriver_PipeInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *coreDriver_PipeInput_Call) Return(err error) *coreDriver_PipeInput_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *coreDriver_PipeInput_Call) RunAndReturn(run func(input io.Reader) error) *coreDriver_PipeInput_Call {
	_c.Call.Return(run)
	return _c
}

// PipeOutput provides a mock function for the type coreDriver
func (_mock *coreDriver) PipeOutput(output io.Writer) error {
	ret := _mock.Called(output)

	if len(ret) == 0 {
		panic("no return value specified for PipeOutput")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer) error); ok {
		r0 = returnFunc(output)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// coreDriver_PipeOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PipeOutput'
type coreDriver_PipeOutput_Call struct {
	*mock.Call
}

// PipeOutput is a helper method to define mock.On call
//   - output io.Writer
func (_e *coreDriver_Expecter) PipeOutput(output interface{}) *coreDriver_PipeOutput_Call {
	return &coreDriver_PipeOutput_Call{Call: _e.mock.On("PipeOutput", output)}
}

func (_c *coreDriver_PipeOutput_Call) Run(run func(output io.Writer)) *coreDriver_PipeOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *coreDriver_PipeOutput_Call) Return(err error) *coreDriver_PipeOutput_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *coreDriver_PipeOutput_Call) RunAndReturn(run func(output io.Writer) error) *coreDriver_PipeOutput_Call {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function for the type coreDriver
func (_mock *coreDriver) Setup() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// coreDriver_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type coreDriver_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
func (_e *coreDriver_Expecter) Setup() *coreDriver_Setup_Call {
	return &coreDriver_Setup_Call{Call: _e.mock.On("Setup")}
}

func (_c *coreDriver_Setup_Call) Run(run func()) *coreDriver_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *coreDriver_Setup_Call) Return(err error) *coreDriver_Setup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *coreDriver_Setup_Call) RunAndReturn(run func() error) *coreDriver_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// TearDown provides a mock function for the type coreDriver
func (_mock *coreDriver) TearDown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TearDown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// coreDriver_TearDown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TearDown'
type coreDriver_TearDown_Call struct {
	*mock.Call
}

// TearDown is a helper method to define mock.On call
func (_e *coreDriver_Expecter) TearDown() *coreDriver_TearDown_Call {
	return &coreDriver_TearDown_Call{Call: _e.mock.On("TearDown")}
}

func (_c *coreDriver_TearDown_Call) Run(run func()) *coreDriver_TearDown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *coreDriver_TearDown_Call) Return(err error) *coreDriver_TearDown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *coreDriver_TearDown_Call) RunAndReturn(run func() error) *coreDriver_TearDown_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type coreDriver
func (_mock *coreDriver) Wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// coreDriver_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type coreDriver_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *coreDriver_Expecter) Wait() *coreDriver_Wait_Call {
	return &coreDriver_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *coreDriver_Wait_Call) Run(run func()) *coreDriver_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *coreDriver_Wait_Call) Return(err error) *coreDriver_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *coreDriver_Wait_Call) RunAndReturn(run func() error) *coreDriver_Wait_Call {
	_c.Call.Return(run)
	return _c
}
