// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksession

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewDriver creates a new instance of Driver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Driver {
	mock := &Driver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Driver is an autogenerated mock type for the Driver type
type Driver struct {
	mock.Mock
}

type Driver_Expecter struct {
	mock *mock.Mock
}

func (_m *Driver) EXPECT() *Driver_Expecter {
	return &Driver_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type Driver
func (_mock *Driver) Start(parentCtx context.Context) error {
	ret := _mock.Called(parentCtx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(parentCtx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Driver_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Driver_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - parentCtx context.Context
func (_e *Driver_Expecter) Start(parentCtx interface{}) *Driver_Start_Call {
	return &Driver_Start_Call{Call: _e.mock.On("Start", parentCtx)}
}

func (_c *Driver_Start_Call) Run(run func(parentCtx context.Context)) *Driver_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Driver_Start_Call) Return(err error) *Driver_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Driver_Start_Call) RunAndReturn(run func(parentCtx context.Context) error) *Driver_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Driver
func (_mock *Driver) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Driver_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Driver_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Driver_Expecter) Stop(ctx interface{}) *Driver_Stop_Call {
	return &Driver_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Driver_Stop_Call) Run(run func(ctx context.Context)) *Driver_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Driver_Stop_Call) Return(err error) *Driver_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Driver_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *Driver_Stop_Call {
	_c.Call.Return(run)
	return _c
}
