// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksession

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// ChangeOutputBufferCapacity provides a mock function for the type Manager
func (_mock *Manager) ChangeOutputBufferCapacity(ctx context.Context, sessionName string, newCap int64, blocking bool) error {
	ret := _mock.Called(ctx, sessionName, newCap, blocking)

	if len(ret) == 0 {
		panic("no return value specified for ChangeOutputBufferCapacity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, bool) error); ok {
		r0 = returnFunc(ctx, sessionName, newCap, blocking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_ChangeOutputBufferCapacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeOutputBufferCapacity'
type Manager_ChangeOutputBufferCapacity_Call struct {
	*mock.Call
}

// ChangeOutputBufferCapacity is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
//   - newCap int64
//   - blocking bool
func (_e *Manager_Expecter) ChangeOutputBufferCapacity(ctx interface{}, sessionName interface{}, newCap interface{}, blocking interface{}) *Manager_ChangeOutputBufferCapacity_Call {
	return &Manager_ChangeOutputBufferCapacity_Call{Call: _e.mock.On("ChangeOutputBufferCapacity", ctx, sessionName, newCap, blocking)}
}

func (_c *Manager_ChangeOutputBufferCapacity_Call) Run(run func(ctx context.Context, sessionName string, newCap int64, blocking bool)) *Manager_ChangeOutputBufferCapacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_ChangeOutputBufferCapacity_Call) Return(err error) *Manager_ChangeOutputBufferCapacity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_ChangeOutputBufferCapacity_Call) RunAndReturn(run func(ctx context.Context, sessionName string, newCap int64, blocking bool) error) *Manager_ChangeOutputBufferCapacity_Call {
	_c.Call.Return(run)
	return _c
}

// HandleChangeOutputBufferCapacity provides a mock function for the type Manager
func (_mock *Manager) HandleChangeOutputBufferCapacity(sessionName string, newCap int64, onComplete func(ctx context.Context, err error)) error {
	ret := _mock.Called(sessionName, newCap, onComplete)

	if len(ret) == 0 {
		panic("no return value specified for HandleChangeOutputBufferCapacity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int64, func(ctx context.Context, err error)) error); ok {
		r0 = returnFunc(sessionName, newCap, onComplete)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_HandleChangeOutputBufferCapacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleChangeOutputBufferCapacity'
type Manager_HandleChangeOutputBufferCapacity_Call struct {
	*mock.Call
}

// HandleChangeOutputBufferCapacity is a helper method to define mock.On call
//   - sessionName string
//   - newCap int64
//   - onComplete func(ctx context.Context, err error)
func (_e *Manager_Expecter) HandleChangeOutputBufferCapacity(sessionName interface{}, newCap interface{}, onComplete interface{}) *Manager_HandleChangeOutputBufferCapacity_Call {
	return &Manager_HandleChangeOutputBufferCapacity_Call{Call: _e.mock.On("HandleChangeOutputBufferCapacity", sessionName, newCap, onComplete)}
}

func (_c *Manager_HandleChangeOutputBufferCapacity_Call) Run(run func(sessionName string, newCap int64, onComplete func(ctx context.Context, err error))) *Manager_HandleChangeOutputBufferCapacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(ctx context.Context, err error)
		if args[2] != nil {
			arg2 = args[2].(func(ctx context.Context, err error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_HandleChangeOutputBufferCapacity_Call) Return(err error) *Manager_HandleChangeOutputBufferCapacity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_HandleChangeOutputBufferCapacity_Call) RunAndReturn(run func(sessionName string, newCap int64, onComplete func(ctx context.Context, err error)) error) *Manager_HandleChangeOutputBufferCapacity_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSessionIPCProcessError provides a mock function for the type Manager
func (_mock *Manager) HandleSessionIPCProcessError(sessionName string, sessionErr error) {
	_mock.Called(sessionName, sessionErr)
	return
}

// Manager_HandleSessionIPCProcessError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSessionIPCProcessError'
type Manager_HandleSessionIPCProcessError_Call struct {
	*mock.Call
}

// HandleSessionIPCProcessError is a helper method to define mock.On call
//   - sessionName string
//   - sessionErr error
func (_e *Manager_Expecter) HandleSessionIPCProcessError(sessionName interface{}, sessionErr interface{}) *Manager_HandleSessionIPCProcessError_Call {
	return &Manager_HandleSessionIPCProcessError_Call{Call: _e.mock.On("HandleSessionIPCProcessError", sessionName, sessionErr)}
}

func (_c *Manager_HandleSessionIPCProcessError_Call) Run(run func(sessionName string, sessionErr error)) *Manager_HandleSessionIPCProcessError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Manager_HandleSessionIPCProcessError_Call) Return() *Manager_HandleSessionIPCProcessError_Call {
	_c.Call.Return()
	return _c
}

func (_c *Manager_HandleSessionIPCProcessError_Call) RunAndReturn(run func(sessionName string, sessionErr error)) *Manager_HandleSessionIPCProcessError_Call {
	_c.Run(run)
	return _c
}

// HandleSessionIdleNotify provides a mock function for the type Manager
func (_mock *Manager) HandleSessionIdleNotify(sessionName string) {
	_mock.Called(sessionName)
	return
}

// Manager_HandleSessionIdleNotify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSessionIdleNotify'
type Manager_HandleSessionIdleNotify_Call struct {
	*mock.Call
}

// HandleSessionIdleNotify is a helper method to define mock.On call
//   - sessionName string
func (_e *Manager_Expecter) HandleSessionIdleNotify(sessionName interface{}) *Manager_HandleSessionIdleNotify_Call {
	return &Manager_HandleSessionIdleNotify_Call{Call: _e.mock.On("HandleSessionIdleNotify", sessionName)}
}

func (_c *Manager_HandleSessionIdleNotify_Call) Run(run func(sessionName string)) *Manager_HandleSessionIdleNotify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_HandleSessionIdleNotify_Call) Return() *Manager_HandleSessionIdleNotify_Call {
	_c.Call.Return()
	return _c
}

func (_c *Manager_HandleSessionIdleNotify_Call) RunAndReturn(run func(sessionName string)) *Manager_HandleSessionIdleNotify_Call {
	_c.Run(run)
	return _c
}

// HandleStartSession provides a mock function for the type Manager
func (_mock *Manager) HandleStartSession(sessionName string, onComplete func(ctx context.Context, err error)) error {
	ret := _mock.Called(sessionName, onComplete)

	if len(ret) == 0 {
		panic("no return value specified for HandleStartSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, func(ctx context.Context, err error)) error); ok {
		r0 = returnFunc(sessionName, onComplete)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_HandleStartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleStartSession'
type Manager_HandleStartSession_Call struct {
	*mock.Call
}

// HandleStartSession is a helper method to define mock.On call
//   - sessionName string
//   - onComplete func(ctx context.Context, err error)
func (_e *Manager_Expecter) HandleStartSession(sessionName interface{}, onComplete interface{}) *Manager_HandleStartSession_Call {
	return &Manager_HandleStartSession_Call{Call: _e.mock.On("HandleStartSession", sessionName, onComplete)}
}

func (_c *Manager_HandleStartSession_Call) Run(run func(sessionName string, onComplete func(ctx context.Context, err error))) *Manager_HandleStartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(ctx context.Context, err error)
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, err error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Manager_HandleStartSession_Call) Return(err error) *Manager_HandleStartSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_HandleStartSession_Call) RunAndReturn(run func(sessionName string, onComplete func(ctx context.Context, err error)) error) *Manager_HandleStartSession_Call {
	_c.Call.Return(run)
	return _c
}

// HandleStopAllSessions provides a mock function for the type Manager
func (_mock *Manager) HandleStopAllSessions(onComplete func(ctx context.Context, err error)) error {
	ret := _mock.Called(onComplete)

	if len(ret) == 0 {
		panic("no return value specified for HandleStopAllSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(ctx context.Context, err error)) error); ok {
		r0 = returnFunc(onComplete)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_HandleStopAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleStopAllSessions'
type Manager_HandleStopAllSessions_Call struct {
	*mock.Call
}

// HandleStopAllSessions is a helper method to define mock.On call
//   - onComplete func(ctx context.Context, err error)
func (_e *Manager_Expecter) HandleStopAllSessions(onComplete interface{}) *Manager_HandleStopAllSessions_Call {
	return &Manager_HandleStopAllSessions_Call{Call: _e.mock.On("HandleStopAllSessions", onComplete)}
}

func (_c *Manager_HandleStopAllSessions_Call) Run(run func(onComplete func(ctx context.Context, err error))) *Manager_HandleStopAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(ctx context.Context, err error)
		if args[0] != nil {
			arg0 = args[0].(func(ctx context.Context, err error))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_HandleStopAllSessions_Call) Return(err error) *Manager_HandleStopAllSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_HandleStopAllSessions_Call) RunAndReturn(run func(onComplete func(ctx context.Context, err error)) error) *Manager_HandleStopAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// HandleStopSession provides a mock function for the type Manager
func (_mock *Manager) HandleStopSession(sessionName string, onComplete func(ctx context.Context, err error)) error {
	ret := _mock.Called(sessionName, onComplete)

	if len(ret) == 0 {
		panic("no return value specified for HandleStopSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, func(ctx context.Context, err error)) error); ok {
		r0 = returnFunc(sessionName, onComplete)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_HandleStopSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleStopSession'
type Manager_HandleStopSession_Call struct {
	*mock.Call
}

// HandleStopSession is a helper method to define mock.On call
//   - sessionName string
//   - onComplete func(ctx context.Context, err error)
func (_e *Manager_Expecter) HandleStopSession(sessionName interface{}, onComplete interface{}) *Manager_HandleStopSession_Call {
	return &Manager_HandleStopSession_Call{Call: _e.mock.On("HandleStopSession", sessionName, onComplete)}
}

func (_c *Manager_HandleStopSession_Call) Run(run func(sessionName string, onComplete func(ctx context.Context, err error))) *Manager_HandleStopSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(ctx context.Context, err error)
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, err error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Manager_HandleStopSession_Call) Return(err error) *Manager_HandleStopSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_HandleStopSession_Call) RunAndReturn(run func(sessionName string, onComplete func(ctx context.Context, err error)) error) *Manager_HandleStopSession_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type Manager
func (_mock *Manager) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Manager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Manager_Expecter) Start(ctx interface{}) *Manager_Start_Call {
	return &Manager_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Manager_Start_Call) Run(run func(ctx context.Context)) *Manager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_Start_Call) Return(err error) *Manager_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_Start_Call) RunAndReturn(run func(ctx context.Context) error) *Manager_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function for the type Manager
func (_mock *Manager) StartSession(ctx context.Context, sessionName string, blocking bool) error {
	ret := _mock.Called(ctx, sessionName, blocking)

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, sessionName, blocking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type Manager_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
//   - blocking bool
func (_e *Manager_Expecter) StartSession(ctx interface{}, sessionName interface{}, blocking interface{}) *Manager_StartSession_Call {
	return &Manager_StartSession_Call{Call: _e.mock.On("StartSession", ctx, sessionName, blocking)}
}

func (_c *Manager_StartSession_Call) Run(run func(ctx context.Context, sessionName string, blocking bool)) *Manager_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_StartSession_Call) Return(err error) *Manager_StartSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_StartSession_Call) RunAndReturn(run func(ctx context.Context, sessionName string, blocking bool) error) *Manager_StartSession_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Manager
func (_mock *Manager) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Manager_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Manager_Expecter) Stop(ctx interface{}) *Manager_Stop_Call {
	return &Manager_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Manager_Stop_Call) Run(run func(ctx context.Context)) *Manager_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_Stop_Call) Return(err error) *Manager_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *Manager_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// StopAllSessions provides a mock function for the type Manager
func (_mock *Manager) StopAllSessions(ctx context.Context, blocking bool) error {
	ret := _mock.Called(ctx, blocking)

	if len(ret) == 0 {
		panic("no return value specified for StopAllSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = returnFunc(ctx, blocking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_StopAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAllSessions'
type Manager_StopAllSessions_Call struct {
	*mock.Call
}

// StopAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
func (_e *Manager_Expecter) StopAllSessions(ctx interface{}, blocking interface{}) *Manager_StopAllSessions_Call {
	return &Manager_StopAllSessions_Call{Call: _e.mock.On("StopAllSessions", ctx, blocking)}
}

func (_c *Manager_StopAllSessions_Call) Run(run func(ctx context.Context, blocking bool)) *Manager_StopAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Manager_StopAllSessions_Call) Return(err error) *Manager_StopAllSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_StopAllSessions_Call) RunAndReturn(run func(ctx context.Context, blocking bool) error) *Manager_StopAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// StopSession provides a mock function for the type Manager
func (_mock *Manager) StopSession(ctx context.Context, sessionName string, blocking bool) error {
	ret := _mock.Called(ctx, sessionName, blocking)

	if len(ret) == 0 {
		panic("no return value specified for StopSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, sessionName, blocking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_StopSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopSession'
type Manager_StopSession_Call struct {
	*mock.Call
}

// StopSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
//   - blocking bool
func (_e *Manager_Expecter) StopSession(ctx interface{}, sessionName interface{}, blocking interface{}) *Manager_StopSession_Call {
	return &Manager_StopSession_Call{Call: _e.mock.On("StopSession", ctx, sessionName, blocking)}
}

func (_c *Manager_StopSession_Call) Run(run func(ctx context.Context, sessionName string, blocking bool)) *Manager_StopSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_StopSession_Call) Return(err error) *Manager_StopSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_StopSession_Call) RunAndReturn(run func(ctx context.Context, sessionName string, blocking bool) error) *Manager_StopSession_Call {
	_c.Call.Return(run)
	return _c
}
