// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksession

import (
	"context"

	"github.com/alwitt/rest-pty/models"
	mock "github.com/stretchr/testify/mock"
)

// NewRunner creates a new instance of Runner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Runner {
	mock := &Runner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

type Runner_Expecter struct {
	mock *mock.Mock
}

func (_m *Runner) EXPECT() *Runner_Expecter {
	return &Runner_Expecter{mock: &_m.Mock}
}

// HandleIPCRequestMessage provides a mock function for the type Runner
func (_mock *Runner) HandleIPCRequestMessage(newMessage models.IPCMessageEnvelope) error {
	ret := _mock.Called(newMessage)

	if len(ret) == 0 {
		panic("no return value specified for HandleIPCRequestMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.IPCMessageEnvelope) error); ok {
		r0 = returnFunc(newMessage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_HandleIPCRequestMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleIPCRequestMessage'
type Runner_HandleIPCRequestMessage_Call struct {
	*mock.Call
}

// HandleIPCRequestMessage is a helper method to define mock.On call
//   - newMessage models.IPCMessageEnvelope
func (_e *Runner_Expecter) HandleIPCRequestMessage(newMessage interface{}) *Runner_HandleIPCRequestMessage_Call {
	return &Runner_HandleIPCRequestMessage_Call{Call: _e.mock.On("HandleIPCRequestMessage", newMessage)}
}

func (_c *Runner_HandleIPCRequestMessage_Call) Run(run func(newMessage models.IPCMessageEnvelope)) *Runner_HandleIPCRequestMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.IPCMessageEnvelope
		if args[0] != nil {
			arg0 = args[0].(models.IPCMessageEnvelope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_HandleIPCRequestMessage_Call) Return(err error) *Runner_HandleIPCRequestMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_HandleIPCRequestMessage_Call) RunAndReturn(run func(newMessage models.IPCMessageEnvelope) error) *Runner_HandleIPCRequestMessage_Call {
	_c.Call.Return(run)
	return _c
}

// HandleStartSession provides a mock function for the type Runner
func (_mock *Runner) HandleStartSession(onComplete func(ctx context.Context, err error)) error {
	ret := _mock.Called(onComplete)

	if len(ret) == 0 {
		panic("no return value specified for HandleStartSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(ctx context.Context, err error)) error); ok {
		r0 = returnFunc(onComplete)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_HandleStartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleStartSession'
type Runner_HandleStartSession_Call struct {
	*mock.Call
}

// HandleStartSession is a helper method to define mock.On call
//   - onComplete func(ctx context.Context, err error)
func (_e *Runner_Expecter) HandleStartSession(onComplete interface{}) *Runner_HandleStartSession_Call {
	return &Runner_HandleStartSession_Call{Call: _e.mock.On("HandleStartSession", onComplete)}
}

func (_c *Runner_HandleStartSession_Call) Run(run func(onComplete func(ctx context.Context, err error))) *Runner_HandleStartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(ctx context.Context, err error)
		if args[0] != nil {
			arg0 = args[0].(func(ctx context.Context, err error))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_HandleStartSession_Call) Return(err error) *Runner_HandleStartSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_HandleStartSession_Call) RunAndReturn(run func(onComplete func(ctx context.Context, err error)) error) *Runner_HandleStartSession_Call {
	_c.Call.Return(run)
	return _c
}

// HandleStopSession provides a mock function for the type Runner
func (_mock *Runner) HandleStopSession(onComplete func(ctx context.Context, err error)) error {
	ret := _mock.Called(onComplete)

	if len(ret) == 0 {
		panic("no return value specified for HandleStopSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(ctx context.Context, err error)) error); ok {
		r0 = returnFunc(onComplete)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_HandleStopSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleStopSession'
type Runner_HandleStopSession_Call struct {
	*mock.Call
}

// HandleStopSession is a helper method to define mock.On call
//   - onComplete func(ctx context.Context, err error)
func (_e *Runner_Expecter) HandleStopSession(onComplete interface{}) *Runner_HandleStopSession_Call {
	return &Runner_HandleStopSession_Call{Call: _e.mock.On("HandleStopSession", onComplete)}
}

func (_c *Runner_HandleStopSession_Call) Run(run func(onComplete func(ctx context.Context, err error))) *Runner_HandleStopSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(ctx context.Context, err error)
		if args[0] != nil {
			arg0 = args[0].(func(ctx context.Context, err error))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_HandleStopSession_Call) Return(err error) *Runner_HandleStopSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_HandleStopSession_Call) RunAndReturn(run func(onComplete func(ctx context.Context, err error)) error) *Runner_HandleStopSession_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSubmitCommands provides a mock function for the type Runner
func (_mock *Runner) HandleSubmitCommands(commands []models.SessionInputCommand, onComplete func(ctx context.Context, err error)) error {
	ret := _mock.Called(commands, onComplete)

	if len(ret) == 0 {
		panic("no return value specified for HandleSubmitCommands")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.SessionInputCommand, func(ctx context.Context, err error)) error); ok {
		r0 = returnFunc(commands, onComplete)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_HandleSubmitCommands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSubmitCommands'
type Runner_HandleSubmitCommands_Call struct {
	*mock.Call
}

// HandleSubmitCommands is a helper method to define mock.On call
//   - commands []models.SessionInputCommand
//   - onComplete func(ctx context.Context, err error)
func (_e *Runner_Expecter) HandleSubmitCommands(commands interface{}, onComplete interface{}) *Runner_HandleSubmitCommands_Call {
	return &Runner_HandleSubmitCommands_Call{Call: _e.mock.On("HandleSubmitCommands", commands, onComplete)}
}

func (_c *Runner_HandleSubmitCommands_Call) Run(run func(commands []models.SessionInputCommand, onComplete func(ctx context.Context, err error))) *Runner_HandleSubmitCommands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.SessionInputCommand
		if args[0] != nil {
			arg0 = args[0].([]models.SessionInputCommand)
		}
		var arg1 func(ctx context.Context, err error)
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, err error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runner_HandleSubmitCommands_Call) Return(err error) *Runner_HandleSubmitCommands_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_HandleSubmitCommands_Call) RunAndReturn(run func(commands []models.SessionInputCommand, onComplete func(ctx context.Context, err error)) error) *Runner_HandleSubmitCommands_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type Runner
func (_mock *Runner) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Runner_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Runner_Expecter) Start(ctx interface{}) *Runner_Start_Call {
	return &Runner_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Runner_Start_Call) Run(run func(ctx context.Context)) *Runner_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_Start_Call) Return(err error) *Runner_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_Start_Call) RunAndReturn(run func(ctx context.Context) error) *Runner_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function for the type Runner
func (_mock *Runner) StartSession(ctx context.Context, blocking bool) error {
	ret := _mock.Called(ctx, blocking)

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = returnFunc(ctx, blocking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type Runner_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
func (_e *Runner_Expecter) StartSession(ctx interface{}, blocking interface{}) *Runner_StartSession_Call {
	return &Runner_StartSession_Call{Call: _e.mock.On("StartSession", ctx, blocking)}
}

func (_c *Runner_StartSession_Call) Run(run func(ctx context.Context, blocking bool)) *Runner_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runner_StartSession_Call) Return(err error) *Runner_StartSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_StartSession_Call) RunAndReturn(run func(ctx context.Context, blocking bool) error) *Runner_StartSession_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Runner
func (_mock *Runner) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Runner_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Runner_Expecter) Stop(ctx interface{}) *Runner_Stop_Call {
	return &Runner_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Runner_Stop_Call) Run(run func(ctx context.Context)) *Runner_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_Stop_Call) Return(err error) *Runner_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *Runner_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// StopSession provides a mock function for the type Runner
func (_mock *Runner) StopSession(ctx context.Context, blocking bool) error {
	ret := _mock.Called(ctx, blocking)

	if len(ret) == 0 {
		panic("no return value specified for StopSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = returnFunc(ctx, blocking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_StopSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopSession'
type Runner_StopSession_Call struct {
	*mock.Call
}

// StopSession is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
func (_e *Runner_Expecter) StopSession(ctx interface{}, blocking interface{}) *Runner_StopSession_Call {
	return &Runner_StopSession_Call{Call: _e.mock.On("StopSession", ctx, blocking)}
}

func (_c *Runner_StopSession_Call) Run(run func(ctx context.Context, blocking bool)) *Runner_StopSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runner_StopSession_Call) Return(err error) *Runner_StopSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_StopSession_Call) RunAndReturn(run func(ctx context.Context, blocking bool) error) *Runner_StopSession_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitCommands provides a mock function for the type Runner
func (_mock *Runner) SubmitCommands(ctx context.Context, commands []models.SessionInputCommand) error {
	ret := _mock.Called(ctx, commands)

	if len(ret) == 0 {
		panic("no return value specified for SubmitCommands")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.SessionInputCommand) error); ok {
		r0 = returnFunc(ctx, commands)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_SubmitCommands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitCommands'
type Runner_SubmitCommands_Call struct {
	*mock.Call
}

// SubmitCommands is a helper method to define mock.On call
//   - ctx context.Context
//   - commands []models.SessionInputCommand
func (_e *Runner_Expecter) SubmitCommands(ctx interface{}, commands interface{}) *Runner_SubmitCommands_Call {
	return &Runner_SubmitCommands_Call{Call: _e.mock.On("SubmitCommands", ctx, commands)}
}

func (_c *Runner_SubmitCommands_Call) Run(run func(ctx context.Context, commands []models.SessionInputCommand)) *Runner_SubmitCommands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.SessionInputCommand
		if args[1] != nil {
			arg1 = args[1].([]models.SessionInputCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runner_SubmitCommands_Call) Return(err error) *Runner_SubmitCommands_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_SubmitCommands_Call) RunAndReturn(run func(ctx context.Context, commands []models.SessionInputCommand) error) *Runner_SubmitCommands_Call {
	_c.Call.Return(run)
	return _c
}
