// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewForTextSessionManager creates a new instance of ForTextSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForTextSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForTextSessionManager {
	mock := &ForTextSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ForTextSessionManager is an autogenerated mock type for the ForTextSessionManager type
type ForTextSessionManager struct {
	mock.Mock
}

type ForTextSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *ForTextSessionManager) EXPECT() *ForTextSessionManager_Expecter {
	return &ForTextSessionManager_Expecter{mock: &_m.Mock}
}

// IPCProcessErrorNotify provides a mock function for the type ForTextSessionManager
func (_mock *ForTextSessionManager) IPCProcessErrorNotify(err error) {
	_mock.Called(err)
	return
}

// ForTextSessionManager_IPCProcessErrorNotify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPCProcessErrorNotify'
type ForTextSessionManager_IPCProcessErrorNotify_Call struct {
	*mock.Call
}

// IPCProcessErrorNotify is a helper method to define mock.On call
//   - err error
func (_e *ForTextSessionManager_Expecter) IPCProcessErrorNotify(err interface{}) *ForTextSessionManager_IPCProcessErrorNotify_Call {
	return &ForTextSessionManager_IPCProcessErrorNotify_Call{Call: _e.mock.On("IPCProcessErrorNotify", err)}
}

func (_c *ForTextSessionManager_IPCProcessErrorNotify_Call) Run(run func(err error)) *ForTextSessionManager_IPCProcessErrorNotify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ForTextSessionManager_IPCProcessErrorNotify_Call) Return() *ForTextSessionManager_IPCProcessErrorNotify_Call {
	_c.Call.Return()
	return _c
}

func (_c *ForTextSessionManager_IPCProcessErrorNotify_Call) RunAndReturn(run func(err error)) *ForTextSessionManager_IPCProcessErrorNotify_Call {
	_c.Run(run)
	return _c
}

// SessionIdleNotify provides a mock function for the type ForTextSessionManager
func (_mock *ForTextSessionManager) SessionIdleNotify() {
	_mock.Called()
	return
}

// ForTextSessionManager_SessionIdleNotify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionIdleNotify'
type ForTextSessionManager_SessionIdleNotify_Call struct {
	*mock.Call
}

// SessionIdleNotify is a helper method to define mock.On call
func (_e *ForTextSessionManager_Expecter) SessionIdleNotify() *ForTextSessionManager_SessionIdleNotify_Call {
	return &ForTextSessionManager_SessionIdleNotify_Call{Call: _e.mock.On("SessionIdleNotify")}
}

func (_c *ForTextSessionManager_SessionIdleNotify_Call) Run(run func()) *ForTextSessionManager_SessionIdleNotify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ForTextSessionManager_SessionIdleNotify_Call) Return() *ForTextSessionManager_SessionIdleNotify_Call {
	_c.Call.Return()
	return _c
}

func (_c *ForTextSessionManager_SessionIdleNotify_Call) RunAndReturn(run func()) *ForTextSessionManager_SessionIdleNotify_Call {
	_c.Run(run)
	return _c
}
