// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktest

import (
	"context"
	"reflect"
	"sync"

	"github.com/alwitt/goutils"
	mock "github.com/stretchr/testify/mock"
)

// NewTaskProcessorForTest creates a new instance of TaskProcessorForTest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskProcessorForTest(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskProcessorForTest {
	mock := &TaskProcessorForTest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TaskProcessorForTest is an autogenerated mock type for the TaskProcessorForTest type
type TaskProcessorForTest struct {
	mock.Mock
}

type TaskProcessorForTest_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskProcessorForTest) EXPECT() *TaskProcessorForTest_Expecter {
	return &TaskProcessorForTest_Expecter{mock: &_m.Mock}
}

// AddToTaskExecutionMap provides a mock function for the type TaskProcessorForTest
func (_mock *TaskProcessorForTest) AddToTaskExecutionMap(parameterType reflect.Type, handler goutils.TaskProcessorSupportHandler) error {
	ret := _mock.Called(parameterType, handler)

	if len(ret) == 0 {
		panic("no return value specified for AddToTaskExecutionMap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(reflect.Type, goutils.TaskProcessorSupportHandler) error); ok {
		r0 = returnFunc(parameterType, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskProcessorForTest_AddToTaskExecutionMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToTaskExecutionMap'
type TaskProcessorForTest_AddToTaskExecutionMap_Call struct {
	*mock.Call
}

// AddToTaskExecutionMap is a helper method to define mock.On call
//   - parameterType reflect.Type
//   - handler goutils.TaskProcessorSupportHandler
func (_e *TaskProcessorForTest_Expecter) AddToTaskExecutionMap(parameterType interface{}, handler interface{}) *TaskProcessorForTest_AddToTaskExecutionMap_Call {
	return &TaskProcessorForTest_AddToTaskExecutionMap_Call{Call: _e.mock.On("AddToTaskExecutionMap", parameterType, handler)}
}

func (_c *TaskProcessorForTest_AddToTaskExecutionMap_Call) Run(run func(parameterType reflect.Type, handler goutils.TaskProcessorSupportHandler)) *TaskProcessorForTest_AddToTaskExecutionMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		var arg1 goutils.TaskProcessorSupportHandler
		if args[1] != nil {
			arg1 = args[1].(goutils.TaskProcessorSupportHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskProcessorForTest_AddToTaskExecutionMap_Call) Return(err error) *TaskProcessorForTest_AddToTaskExecutionMap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskProcessorForTest_AddToTaskExecutionMap_Call) RunAndReturn(run func(parameterType reflect.Type, handler goutils.TaskProcessorSupportHandler) error) *TaskProcessorForTest_AddToTaskExecutionMap_Call {
	_c.Call.Return(run)
	return _c
}

// SetTaskExecutionMap provides a mock function for the type TaskProcessorForTest
func (_mock *TaskProcessorForTest) SetTaskExecutionMap(newMap map[reflect.Type]goutils.TaskProcessorSupportHandler) error {
	ret := _mock.Called(newMap)

	if len(ret) == 0 {
		panic("no return value specified for SetTaskExecutionMap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[reflect.Type]goutils.TaskProcessorSupportHandler) error); ok {
		r0 = returnFunc(newMap)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskProcessorForTest_SetTaskExecutionMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTaskExecutionMap'
type TaskProcessorForTest_SetTaskExecutionMap_Call struct {
	*mock.Call
}

// SetTaskExecutionMap is a helper method to define mock.On call
//   - newMap map[reflect.Type]goutils.TaskProcessorSupportHandler
func (_e *TaskProcessorForTest_Expecter) SetTaskExecutionMap(newMap interface{}) *TaskProcessorForTest_SetTaskExecutionMap_Call {
	return &TaskProcessorForTest_SetTaskExecutionMap_Call{Call: _e.mock.On("SetTaskExecutionMap", newMap)}
}

func (_c *TaskProcessorForTest_SetTaskExecutionMap_Call) Run(run func(newMap map[reflect.Type]goutils.TaskProcessorSupportHandler)) *TaskProcessorForTest_SetTaskExecutionMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[reflect.Type]goutils.TaskProcessorSupportHandler
		if args[0] != nil {
			arg0 = args[0].(map[reflect.Type]goutils.TaskProcessorSupportHandler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskProcessorForTest_SetTaskExecutionMap_Call) Return(err error) *TaskProcessorForTest_SetTaskExecutionMap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskProcessorForTest_SetTaskExecutionMap_Call) RunAndReturn(run func(newMap map[reflect.Type]goutils.TaskProcessorSupportHandler) error) *TaskProcessorForTest_SetTaskExecutionMap_Call {
	_c.Call.Return(run)
	return _c
}

// StartEventLoop provides a mock function for the type TaskProcessorForTest
func (_mock *TaskProcessorForTest) StartEventLoop(wg *sync.WaitGroup) error {
	ret := _mock.Called(wg)

	if len(ret) == 0 {
		panic("no return value specified for StartEventLoop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sync.WaitGroup) error); ok {
		r0 = returnFunc(wg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskProcessorForTest_StartEventLoop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartEventLoop'
type TaskProcessorForTest_StartEventLoop_Call struct {
	*mock.Call
}

// StartEventLoop is a helper method to define mock.On call
//   - wg *sync.WaitGroup
func (_e *TaskProcessorForTest_Expecter) StartEventLoop(wg interface{}) *TaskProcessorForTest_StartEventLoop_Call {
	return &TaskProcessorForTest_StartEventLoop_Call{Call: _e.mock.On("StartEventLoop", wg)}
}

func (_c *TaskProcessorForTest_StartEventLoop_Call) Run(run func(wg *sync.WaitGroup)) *TaskProcessorForTest_StartEventLoop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sync.WaitGroup
		if args[0] != nil {
			arg0 = args[0].(*sync.WaitGroup)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskProcessorForTest_StartEventLoop_Call) Return(err error) *TaskProcessorForTest_StartEventLoop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskProcessorForTest_StartEventLoop_Call) RunAndReturn(run func(wg *sync.WaitGroup) error) *TaskProcessorForTest_StartEventLoop_Call {
	_c.Call.Return(run)
	return _c
}

// StopEventLoop provides a mock function for the type TaskProcessorForTest
func (_mock *TaskProcessorForTest) StopEventLoop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopEventLoop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskProcessorForTest_StopEventLoop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopEventLoop'
type TaskProcessorForTest_StopEventLoop_Call struct {
	*mock.Call
}

// StopEventLoop is a helper method to define mock.On call
func (_e *TaskProcessorForTest_Expecter) StopEventLoop() *TaskProcessorForTest_StopEventLoop_Call {
	return &TaskProcessorForTest_StopEventLoop_Call{Call: _e.mock.On("StopEventLoop")}
}

func (_c *TaskProcessorForTest_StopEventLoop_Call) Run(run func()) *TaskProcessorForTest_StopEventLoop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskProcessorForTest_StopEventLoop_Call) Return(err error) *TaskProcessorForTest_StopEventLoop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskProcessorForTest_StopEventLoop_Call) RunAndReturn(run func() error) *TaskProcessorForTest_StopEventLoop_Call {
	_c.Call.Return(run)
	return _c
}

// Submit provides a mock function for the type TaskProcessorForTest
func (_mock *TaskProcessorForTest) Submit(ctx context.Context, newTaskParam interface{}) error {
	ret := _mock.Called(ctx, newTaskParam)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = returnFunc(ctx, newTaskParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskProcessorForTest_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type TaskProcessorForTest_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - newTaskParam interface{}
func (_e *TaskProcessorForTest_Expecter) Submit(ctx interface{}, newTaskParam interface{}) *TaskProcessorForTest_Submit_Call {
	return &TaskProcessorForTest_Submit_Call{Call: _e.mock.On("Submit", ctx, newTaskParam)}
}

func (_c *TaskProcessorForTest_Submit_Call) Run(run func(ctx context.Context, newTaskParam interface{})) *TaskProcessorForTest_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskProcessorForTest_Submit_Call) Return(err error) *TaskProcessorForTest_Submit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskProcessorForTest_Submit_Call) RunAndReturn(run func(ctx context.Context, newTaskParam interface{}) error) *TaskProcessorForTest_Submit_Call {
	_c.Call.Return(run)
	return _c
}
