// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockworkspace

import (
	"context"

	"github.com/alwitt/rest-pty/workspace"
	mock "github.com/stretchr/testify/mock"
)

// NewCairnClient creates a new instance of CairnClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCairnClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CairnClient {
	mock := &CairnClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CairnClient is an autogenerated mock type for the CairnClient type
type CairnClient struct {
	mock.Mock
}

type CairnClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CairnClient) EXPECT() *CairnClient_Expecter {
	return &CairnClient_Expecter{mock: &_m.Mock}
}

// FetchWorkspace provides a mock function for the type CairnClient
func (_mock *CairnClient) FetchWorkspace(ctxt context.Context, name string) (workspace.Workspace, error) {
	ret := _mock.Called(ctxt, name)

	if len(ret) == 0 {
		panic("no return value specified for FetchWorkspace")
	}

	var r0 workspace.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (workspace.Workspace, error)); ok {
		return returnFunc(ctxt, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) workspace.Workspace); ok {
		r0 = returnFunc(ctxt, name)
	} else {
		r0 = ret.Get(0).(workspace.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctxt, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CairnClient_FetchWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchWorkspace'
type CairnClient_FetchWorkspace_Call struct {
	*mock.Call
}

// FetchWorkspace is a helper method to define mock.On call
//   - ctxt context.Context
//   - name string
func (_e *CairnClient_Expecter) FetchWorkspace(ctxt interface{}, name interface{}) *CairnClient_FetchWorkspace_Call {
	return &CairnClient_FetchWorkspace_Call{Call: _e.mock.On("FetchWorkspace", ctxt, name)}
}

func (_c *CairnClient_FetchWorkspace_Call) Run(run func(ctxt context.Context, name string)) *CairnClient_FetchWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CairnClient_FetchWorkspace_Call) Return(workspace1 workspace.Workspace, err error) *CairnClient_FetchWorkspace_Call {
	_c.Call.Return(workspace1, err)
	return _c
}

func (_c *CairnClient_FetchWorkspace_Call) RunAndReturn(run func(ctxt context.Context, name string) (workspace.Workspace, error)) *CairnClient_FetchWorkspace_Call {
	_c.Call.Return(run)
	return _c
}
